# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# Debug mod
debug: false

# Typ serveru
server: lobby

# Zmena casu podle real-time
timer: false

# Prefix v tablistu pres display-name
tablist-prefixes: false

## Sezóny ##
seasons:
 # Vanocni update zahrnujici kalendar + efekty
 christmas: false
 # Efekty po lobby (ohnostroje)
 silvester: false

server-utils:
 # Pokud ma lobby resetovat tydenni hlasy (default: false)
 reset-week-votes: false

 # Pokud ma lobby resetovat denni odmeny.
 reset-daily-rewards: false

 # Pokud ma lobby resetovat mesicni odmeny pro VIP
 reset-monthly-rewards: false

## Spawn Příkaz ##
# Pouprav si to zde, podle toho, jak to je
spawn-command:
  # auto-get = Teleportuje to hráče na spawn světu, kde se hráč nachází
  auto-get: false
  location:
    world-name: lobby_4
    x: 349.5
    y: 78.5
    z: 212.5
    yaw: -90.0
    pitch: 0.0

coinshop-tags:
  - test
